### ISSUE TITLE
[VH] Incorrect comparison of DCC version and rule version

### ISSUE THREAD

**Issue by mlenkeit** [eu-digital-green-certificates/dgc-certlogic-android#18]
## Describe the bug

The current implementation is comparing the `ver` attribute of the DCC/hcert  with the `Version` attribute of the rule:

https://github.com/eu-digital-green-certificates/dgc-certlogic-android/blob/bc467afcd8375ff5f579f9cac5bcfba74b55fcd7/engine/src/main/java/dgca/verifier/app/engine/DefaultCertLogicEngine.kt#L73

That's like comparing cars and apples.

## Expected behaviour

Compare `ver` against `SchemaVersion`

## Steps to reproduce the issue

look at the code

## Technical details

n/a

## Possible Fix

Compare `ver` against `SchemaVersion`

## Additional context

n/a

**Comment by oleksandrsarapulovgl** [comment]
PR: https://github.com/eu-digital-green-certificates/dgc-certlogic-android/pull/33

**Comment by mlenkeit** [comment]
LGTM!
