### ISSUE TITLE
Test `ConverterTest.testConverter()` fails locally

### ISSUE THREAD

**Issue by d4rken** [eu-digital-green-certificates/dgc-certlogic-android#19]
Test `ConverterTest.testConverter()` fails locally:

https://github.com/eu-digital-green-certificates/dgc-certlogic-android/blob/bc467afcd8375ff5f579f9cac5bcfba74b55fcd7/engine/src/test/java/dgca/verifier/app/engine/data/source/local/ConvertersTest.kt#L34-L45

```java
junit.framework.AssertionFailedError: expected:<2021-06-30T14:54:51.748565Z> but was:<2021-06-30T14:54:51.748Z>
Expected :2021-06-30T14:54:51.748565Z
Actual   :2021-06-30T14:54:51.748Z
```

Code was a checkout of the current main branch: https://github.com/eu-digital-green-certificates/dgc-certlogic-android/commit/bc467afcd8375ff5f579f9cac5bcfba74b55fcd7

Run via Android Studio 4.2.3.

**Comment by oleksandrsarapulovgl** [comment]
PR: https://github.com/eu-digital-green-certificates/dgc-certlogic-android/pull/42
