### ISSUE TITLE
[VH] Parameter `issuerCountryCode` missing in ExternalParameter

### ISSUE THREAD

**Issue by mlenkeit** [eu-digital-green-certificates/dgc-certlogic-android#25]
## Describe the bug

The parameter `issuerCountryCode` is missing in ExternalParameter:

https://github.com/eu-digital-green-certificates/dgc-certlogic-android/blob/f8d9d3d0fdac559bd2ce98a06661756208a176d2/engine/src/main/java/dgca/verifier/app/engine/data/ExternalParameter.kt#L48-L64

## Expected behaviour

The parameter `issuerCountryCode` can be set.

## Steps to reproduce the issue

see code

## Technical details

n/a

## Possible Fix

add the parameter

## Additional context

the specification describes this parameter as part of the external parameters

**Comment by oleksandrsarapulovgl** [comment]
PR: https://github.com/eu-digital-green-certificates/dgc-certlogic-android/pull/33

**Comment by mlenkeit** [comment]
LGTM!
