### ISSUE TITLE
Check for `Engine` attribute missing

### ISSUE THREAD

**Issue by mlenkeit** [eu-digital-green-certificates/dgc-certlogic-android#27]
## Describe the bug

There is currently no check for the value of the `Engine` attribute of a rule:

https://github.com/eu-digital-green-certificates/dgc-certlogic-android/blob/f8d9d3d0fdac559bd2ce98a06661756208a176d2/engine/src/main/java/dgca/verifier/app/engine/DefaultCertLogicEngine.kt#L68-L100

## Expected behaviour

If a rule has the attribute `Engine` with a value other than `CERTLOGIC`, the rule is not evaluated but reported as `open`.

## Steps to reproduce the issue

see code

## Technical details

n/a

## Possible Fix

add `if` statement

## Additional context

related to https://github.com/eu-digital-green-certificates/dgc-certlogic-ios/issues/26

**Comment by oleksandrsarapulovgl** [comment]
PR: https://github.com/eu-digital-green-certificates/dgc-certlogic-android/pull/33

**Comment by mlenkeit** [comment]
LGTM!
