### ISSUE TITLE
[VH] Rules that fail with a (technical) exceptions should be reported as Open instead of propagating the exception

### ISSUE THREAD

**Issue by mlenkeit** [eu-digital-green-certificates/dgc-certlogic-android#28]
## Describe the bug

When a rule fails with a (technical) exception, the exception is populated to the caller:

https://github.com/eu-digital-green-certificates/dgc-certlogic-android/blob/f8d9d3d0fdac559bd2ce98a06661756208a176d2/engine/src/main/java/dgca/verifier/app/engine/DefaultCertLogicEngine.kt#L68-L100

## Expected behaviour

Any exceptions that might be thrown should be caught and mapped to `open`.

## Steps to reproduce the issue

see code

## Technical details

n/a

## Possible Fix

try-catch statement + map to `open`

## Additional context

n/a

**Comment by oleksandrsarapulovgl** [comment]
PR: https://github.com/eu-digital-green-certificates/dgc-certlogic-android/pull/33

**Comment by mlenkeit** [comment]
LGTM, thanks for the fix!
