### ISSUE TITLE
Reduce Package Dependecies

### ISSUE THREAD

**Issue by SchulzeStTSI** [eu-digital-green-certificates/dgc-certlogic-android#32]
The current implementation contains dependencies to room, retrofit and other dependencies which can result in conflicts in other apps by using this module. To reduce this dependencies the used componentens should be abstracted by interfaces, and the implementation of the interfaces should be passed to the verifier/wallet app. This should reduce the used dependencies by the module. After this refactoring, the module can be released as seperate package.

**Comment by oleksandrsarapulovgl** [comment]
PRs:
https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/pull/164
https://github.com/eu-digital-green-certificates/dgca-wallet-app-android/pull/92
https://github.com/eu-digital-green-certificates/dgc-certlogic-android/pull/48
