### ISSUE TITLE
[VH] Private fields of External Parameters not serialized and passed to rule engine (regression)

### ISSUE THREAD

**Issue by mlenkeit** [eu-digital-green-certificates/dgc-certlogic-android#36]
## Describe the bug

Private fields of the External Parameter class don't seem to be represented in the JSON-serialized representation of the object and thus not passed to the rule engine to be accessed by the rules.

https://github.com/eu-digital-green-certificates/dgc-certlogic-android/blob/75883ece96ae3dd5e61d6f6f659942469be2f892/engine/src/main/java/dgca/verifier/app/engine/data/ExternalParameter.kt#L49-L57

This particularly includes `valueSets`, which should definitely be passed to the rules, and other fields.

## Expected behaviour

External parameters such as `valueSets` can be access by the rules.

## Steps to reproduce the issue

Run this rule for example:

```javascript
{
  "and": [
    {
      "if": [
        {
          "var": "external.valueSets.covid-19-lab-result.0"
        },
        true,
        false
      ]
    },
    {
      "reduce": [
        {
          "var": "external.valueSets.covid-19-lab-result"
        },
        {
          "and": [
            {
              "in": [
                {
                  "var": "current"
                },
                [
                  "260415000",
                  "260373001"
                ]
              ]
            },
            {
              "var": "accumulator"
            }
          ]
        },
        true
      ]
    }
  ]
}
```

## Technical details

n/a

## Possible Fix

Roll back parts of https://github.com/eu-digital-green-certificates/dgc-certlogic-android/commit/75883ece96ae3dd5e61d6f6f659942469be2f892

## Additional context

Regression introduced with https://github.com/eu-digital-green-certificates/dgc-certlogic-android/commit/75883ece96ae3dd5e61d6f6f659942469be2f892

**Comment by oleksandrsarapulovgl** [comment]
PR: https://github.com/eu-digital-green-certificates/dgc-certlogic-android/pull/38

**Comment by mlenkeit** [comment]
LGTM, thanks for the fix!
