### ISSUE TITLE
Validation result `open` not supported

### ISSUE THREAD

**Issue by mlenkeit** [eu-digital-green-certificates/dgc-certlogic-android#4]
## Describe the bug

With the current implementation, rules evaluate to either `pass` or `fail` but not to `open`:

https://github.com/eu-digital-green-certificates/dgc-certlogic-android/blob/d9bd5136036f0db3c2648d70916cbaeb0851b2a3/engine/src/main/java/dgca/verifier/app/engine/DefaultCertLogicEngine.kt#L70-L73

## Expected behaviour

- Determine `open` based on the `EngineVersion` (see also https://github.com/eu-digital-green-certificates/dgc-certlogic-ios/issues/6)
- use `open` is the validation fails for technical reason (see also https://github.com/eu-digital-green-certificates/dgc-certlogic-ios/issues/5)

## Steps to reproduce the issue

look at the code

## Technical details

n/a

## Possible Fix

see expected behavior

## Additional context

n/a

**Comment by oleksandrsarapulovgl** [comment]
PR: https://github.com/eu-digital-green-certificates/dgc-certlogic-android/pull/14

**Comment by mlenkeit** [comment]
I think this is not quite right yet, but I'm closing this in favor of https://github.com/eu-digital-green-certificates/dgc-certlogic-android/issues/28
